services:
  mqtt-server:
    build: .
    container_name: mqtt-server-container
    env_file:
      - .env
    ports:
      - "1883:1883"    # MQTT
      - "8883:8883"    # MQTT WebSocket  
      - "3001:3001"    # Web server
    volumes:
      - ./logs:/app/logs
      - ./uci:/app/uci
      - ./uci_backup:/app/uci_backup
    restart: unless-stopped